defaults:
  name: "&d&lDrag√≥n Personal"
  scale: 1.3

flight:
  speed: 0.9
  boost_speed: 1.6

  ascend_pitch: -20
  descend_pitch: 25
  ascend_speed: 0.55
  descend_speed: 0.40

  max_y: 320

stamina:
  max: 100.0
  drain_per_tick_boost: 0.45
  regen_per_tick_normal: 0.20
  regen_per_tick_offmount: 0.45
  low_stamina_slowdown: true

visual:
  head_item: "DRAGON_HEAD"
  body_item: "BLACK_CONCRETE"
  wing_item: "ELYTRA"
  tail_item: "BLACKSTONE"
